name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Kodu Çek
      uses: actions/checkout@v2

    - name: Visual Studio ve Selenium Kurulumu
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.WebBuildTools --includeRecommended --includeOptional"
        choco install selenium-chromedriver
        choco install googlechrome

    - name: .NET Core Kur
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Bağımlılıkları Yükle
      run: dotnet restore

    - name: Build Yap
      run: dotnet build --configuration Release --no-restore

    - name: Selenium Testlerini Çalıştır
      run: |
        echo "Selenium testlerini çalıştır"
        python ./tests/AdminLoginTest.py
        python ./tests/BirimTestleri.py
        python ./tests/test_AdminPanel.py
