name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Kodu Çek
      uses: actions/checkout@v2

    - name: Visual Studio ve Gerekli Bileşenleri Kur
      run: |
        choco install visualstudio-installer
        vs_installer.exe install --quiet --wait --norestart --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools Microsoft.VisualStudio.Workload.NetCoreBuildTools Microsoft.VisualStudio.Component.WebDeploy Microsoft.VisualStudio.ComponentGroup.Web Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions Microsoft.VisualStudio.Component.WebBuildTools Microsoft.VisualStudio.Component.IISExpress Microsoft.VisualStudio.Component.Client.Web Microsoft.VisualStudio.ComponentGroup.AzureFunctions --includeRecommended --includeOptional

    - name: .NET Core Kur
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Bağımlılıkları Yükle
      run: dotnet restore

    - name: Build Yap
      run: dotnet build --configuration Release --no-restore

    - name: Selenium Testlerini Çalıştır
      run: |
        echo "Selenium testlerini çalıştır"
        python ./tests/AdminLoginTest.py
        python ./tests/BirimTestleri.py
        python ./tests/test_AdminPanel.py
